# Generated by Django 4.2 on 2023-12-02 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('UserType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('CandidateID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('FullName', models.CharField(max_length=255)),
                ('Resume', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('RecruiterID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('CompanyName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('MessageID', models.AutoField(primary_key=True, serialize=False)),
                ('MessageContent', models.TextField()),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('ReceiverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.user')),
                ('SenderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('JobTitle', models.CharField(max_length=255)),
                ('JobDescription', models.TextField()),
                ('Location', models.CharField(max_length=255)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RecruiterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ApplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('ApplicationDate', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(max_length=20)),
                ('JobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('CandidateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidate')),
            ],
        ),
    ]
